### ISSUE TITLE
The Project doesn't have config.json

### ISSUE THREAD

**Issue by free-archer** [BluemediaGER/Timechamp#31]
Hi!
I try to run app and give a mistake:

```
06.04.2022 13:32:50.211 [main] INFO ConfigUtil - Environmental variable TIMECHAMP_CONFIG is not present. Falling back to default config location.
06.04.2022 13:32:50.397 [main] ERRORConfigUtil - Failed to parse config file config.json in path 
```

What should it contain?

**Comment by BluemediaGER** [comment]
Hi.
Please note that Timechamp is in a very early stage of development. Most of the actual functionality is not yet implemented and the project can be severely broken at any point. Documentation is missing for the most part. I will not address any issues that may arise in the current phase of development.

Timechamp needs a configuration file called `config.json`. You can either specify the folder where this file is located in the `TIMECHAMP_CONFIG` environment variable, or put the file in the same folder as the JAR file itself (default location).

For the required content you can take a look at the [Config class](https://github.com/BluemediaGER/Timechamp/blob/development/backend/src/main/java/dev/bluemedia/timechamp/model/config/Config.java). But actually only the `databaseJDBCUrl` property is mandatory.
